### ISSUE TITLE
DeepL message: Failed to fetch

### ISSUE THREAD

**Issue by GitAddviso** [mountbatt/deepl-translation-chrome#1]
Hello,

Interesting extension, but doesn't seem to work. I get this message "DeepL message: Failed to fetch", when I translate the content of an input or textarea. Tested with a free API account.

Any idea?

Thanks

**Comment by mountbatt** [comment]
@GitAddviso have you set the free API url and used a free API key? My same setup is working here at the moment …

**Comment by GitAddviso** [comment]
Yes. Got an account API free. I set the free API url and the Key. Would like to use it for a project under Kirby.

**Comment by mountbatt** [comment]
@GitAddviso will get back to you later today, let me do some checks …

**Comment by mountbatt** [comment]
@GitAddviso Can you send me some screenshots or check the Chrome Developer Console for any detailed message? I cant reproduce it here … but want to help you …

**Comment by GitAddviso** [comment]
Hello,
I had set the App on a specific website, which seems to be too restrictive. I set All websites, and now it's working nice.
Just sometimes some html tag are not parsed correctly, so you have to select carefully each paragraph of text, but it's okay.

Regards.

**Comment by mountbatt** [comment]
@GitAddviso Great! Good hint. Will add it to the setup instructions. I just updated the service worker file and added 'tag_handling=html' to the api call. This should help to keep html-tags intact!

**Comment by mountbatt** [comment]
@GitAddviso I just released version [0.3 ](https://github.com/mountbatt/deepl-translation-chrome/releases/tag/0.3) with a new option to enable "html-tag handling".
